// ============================================================================
// VOCABULARY — 100 items, tagged for daily mission rotation.
// V1 expands to 500. V1.5 to 2,000.
// ============================================================================

import type { ContentItem } from "@/lib/types";

function vocab(
  id: string,
  word: string,
  partOfSpeech: string,
  definition: string,
  example: string,
  topic: string,
  collocations: string[] = [],
  profiles: ContentItem["profileTags"] = ["general_academic"],
  band: ContentItem["difficulty"] = "band6_5",
): ContentItem {
  return {
    id,
    skill: "vocabulary",
    type: "vocabulary_drill",
    title: `Vocabulary: ${word}`,
    topicTags: [topic],
    profileTags: profiles,
    difficulty: band,
    estimatedMinutes: 2,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      word,
      partOfSpeech,
      definition,
      example,
      collocations,
      topic,
    },
  };
}

export const VOCABULARY_ITEMS: ContentItem[] = [
  vocab("voc-001", "regulation", "noun", "a rule or directive made by an authority", "Strict regulation of high-risk technologies is becoming more common.", "law", ["strict regulation", "regulatory framework", "deregulation"], ["law_public_policy", "technology_ai", "business_finance"], "band6_5"),
  vocab("voc-002", "accountability", "noun", "the fact of being responsible for decisions", "The new law increased accountability for senior officials.", "law", ["political accountability", "corporate accountability"], ["law_public_policy", "business_finance"], "band7_0"),
  vocab("voc-003", "transparency", "noun", "openness about decisions and processes", "The platform's transparency report is published every quarter.", "policy", ["lack of transparency", "demand for transparency"], ["law_public_policy", "technology_ai"], "band6_5"),
  vocab("voc-004", "proportionality", "noun", "the quality of being reasonable in scale", "Courts review whether the response is in proportion to the harm.", "law", ["principle of proportionality", "proportional response"], ["law_public_policy"], "band7_0"),
  vocab("voc-005", "consumer protection", "noun", "laws that defend buyers from unfair practices", "Consumer protection rules require clearer pricing online.", "law", ["strengthen consumer protection"], ["law_public_policy", "business_finance"], "band6_5"),
  vocab("voc-006", "legal certainty", "noun", "the predictability of how the law applies", "Investors value legal certainty when entering new markets.", "law", ["lack of legal certainty"], ["law_public_policy", "business_finance"], "band7_0"),
  vocab("voc-007", "public interest", "noun", "the welfare of the general public", "The court ruled the disclosure was in the public interest.", "policy", ["serve the public interest"], ["law_public_policy"], "band6_5"),
  vocab("voc-008", "data privacy", "noun", "the right to control personal information", "Data privacy has become a major concern for users.", "technology", ["protect data privacy", "data privacy laws"], ["technology_ai", "law_public_policy"], "band6_5"),
  vocab("voc-009", "financial inclusion", "noun", "access to financial services for everyone", "Mobile banking has improved financial inclusion in rural areas.", "finance", ["promote financial inclusion"], ["business_finance"], "band7_0"),
  vocab("voc-010", "anti-money laundering", "noun", "laws that prevent hiding illegal money", "Anti-money laundering rules apply to all major banks.", "finance", ["AML compliance", "AML regulations"], ["law_public_policy", "business_finance"], "band7_0"),
  vocab("voc-011", "digital assets", "noun", "assets that exist in digital form", "Digital assets are now part of many investment portfolios.", "finance", ["digital asset regulation"], ["business_finance", "technology_ai"], "band7_0"),
  vocab("voc-012", "cross-border cooperation", "noun", "joint action between countries", "Cross-border cooperation is essential for tackling cybercrime.", "policy", ["strengthen cross-border cooperation"], ["law_public_policy"], "band7_0"),
  vocab("voc-013", "access to justice", "noun", "the ability of people to use legal systems fairly", "Legal aid programs help low-income groups with access to justice.", "law", ["improve access to justice"], ["law_public_policy"], "band7_0"),
  vocab("voc-014", "institutional reform", "noun", "changes to the structure of an organisation", "Institutional reform is needed to restore public trust.", "policy", ["push for institutional reform"], ["law_public_policy"], "band7_0"),
  vocab("voc-015", "innovation", "noun", "a new idea, method, or product", "Innovation drives long-term economic growth.", "technology", ["foster innovation", "drive innovation"], ["technology_ai", "business_finance", "general_academic"], "band6_0"),
  vocab("voc-016", "disruption", "noun", "a major change to an industry", "Streaming services caused the disruption of traditional broadcasting.", "business", ["digital disruption", "industry disruption"], ["business_finance", "technology_ai"], "band6_5"),
  vocab("voc-017", "scalable", "adjective", "able to grow without losing quality", "The cloud platform is highly scalable.", "technology", ["scalable solution", "scalable architecture"], ["technology_ai", "business_finance"], "band6_5"),
  vocab("voc-018", "algorithmic", "adjective", "relating to step-by-step procedures or rules", "Algorithmic decisions can affect access to credit.", "technology", ["algorithmic bias", "algorithmic transparency"], ["technology_ai", "law_public_policy"], "band7_0"),
  vocab("voc-019", "automation", "noun", "use of machines to do tasks previously done by people", "Automation has reduced the cost of routine office work.", "technology", ["automation of tasks", "process automation"], ["technology_ai", "business_finance"], "band6_5"),
  vocab("voc-020", "cybersecurity", "noun", "protection of computer systems from attack", "Cybersecurity is now a board-level concern.", "technology", ["cybersecurity threats", "cybersecurity framework"], ["technology_ai", "business_finance", "law_public_policy"], "band6_5"),
  vocab("voc-021", "workforce", "noun", "all the people working in a particular industry", "The workforce is rapidly reskilling to keep up with AI.", "work", ["workforce development", "future of work"], ["business_finance", "technology_ai"], "band6_0"),
  vocab("voc-022", "reskilling", "noun", "learning new skills for a different job", "Many governments fund reskilling programs for displaced workers.", "work", ["reskilling initiatives"], ["business_finance", "education"], "band6_5"),
  vocab("voc-023", "gig economy", "noun", "an economy based on short-term contracts", "The gig economy has changed how people think about retirement.", "work", ["growth of the gig economy"], ["business_finance"], "band7_0"),
  vocab("voc-024", "labour market", "noun", "the supply of workers and demand for work", "The labour market is tight in several developed economies.", "work", ["labour market participation"], ["business_finance"], "band6_5"),
  vocab("voc-025", "productivity", "noun", "the rate at which work is produced", "Productivity growth has slowed in many advanced economies.", "work", ["productivity gains", "labour productivity"], ["business_finance"], "band6_5"),
  vocab("voc-026", "sustainability", "noun", "the ability to maintain something over time", "Sustainability is central to long-term business planning.", "environment", ["environmental sustainability", "sustainability goals"], ["environment_sustainability", "business_finance"], "band6_0"),
  vocab("voc-027", "emissions", "noun", "gases or particles released into the atmosphere", "Net-zero emissions targets require major investment.", "environment", ["carbon emissions", "reduce emissions"], ["environment_sustainability", "technology_ai"], "band6_0"),
  vocab("voc-028", "renewable", "adjective", "able to be replaced naturally", "Renewable energy now accounts for over 30% of electricity in some countries.", "environment", ["renewable energy", "renewable sources"], ["environment_sustainability", "technology_ai"], "band6_0"),
  vocab("voc-029", "biodiversity", "noun", "the variety of plant and animal life", "Biodiversity loss is one of the most pressing environmental issues.", "environment", ["protect biodiversity"], ["environment_sustainability"], "band6_5"),
  vocab("voc-030", "urbanisation", "noun", "the process of population shift to cities", "Rapid urbanisation is putting pressure on housing and transport.", "cities", ["urbanisation trends"], ["environment_sustainability", "law_public_policy"], "band6_5"),
  vocab("voc-031", "infrastructure", "noun", "basic systems and services that a country uses", "Investment in public infrastructure is essential for growth.", "cities", ["critical infrastructure", "infrastructure investment"], ["general_academic", "business_finance", "law_public_policy"], "band6_0"),
  vocab("voc-032", "congestion", "noun", "the state of being crowded or blocked", "Traffic congestion in major cities costs billions in lost time.", "cities", ["traffic congestion", "reduce congestion"], ["environment_sustainability", "general_academic"], "band6_0"),
  vocab("voc-033", "affordability", "noun", "the quality of being affordable", "Housing affordability has worsened in many capital cities.", "cities", ["housing affordability", "affordability crisis"], ["general_academic", "law_public_policy"], "band6_5"),
  vocab("voc-034", "gentrification", "noun", "the renewal of an area leading to displacement of residents", "Gentrification can change the character of a neighbourhood quickly.", "cities", ["process of gentrification"], ["general_academic", "law_public_policy"], "band7_0"),
  vocab("voc-035", "public health", "noun", "the health of the population as a whole", "Public health systems were tested by the recent pandemic.", "health", ["public health policy"], ["medicine_healthcare", "law_public_policy"], "band6_5"),
  vocab("voc-036", "preventive care", "noun", "healthcare aimed at preventing illness", "Preventive care reduces long-term costs.", "health", ["preventive care services"], ["medicine_healthcare"], "band7_0"),
  vocab("voc-037", "diagnostic", "adjective", "relating to the identification of illness", "Diagnostic tools have improved with machine learning.", "health", ["diagnostic accuracy"], ["medicine_healthcare", "technology_ai"], "band6_5"),
  vocab("voc-038", "epidemic", "noun", "a widespread occurrence of an illness", "The country acted quickly to contain the epidemic.", "health", ["epidemic response"], ["medicine_healthcare"], "band6_0"),
  vocab("voc-039", "vaccination", "noun", "the act of giving a vaccine", "Vaccination rates among adults have declined.", "health", ["vaccination coverage", "vaccination program"], ["medicine_healthcare"], "band6_0"),
  vocab("voc-040", "antibiotic resistance", "noun", "the ability of bacteria to resist drugs", "Antibiotic resistance is a growing global health threat.", "health", ["antibiotic resistance crisis"], ["medicine_healthcare"], "band7_0"),
  vocab("voc-041", "curriculum", "noun", "the subjects studied in a course", "The school updated its curriculum to include coding.", "education", ["curriculum design", "national curriculum"], ["education"], "band6_0"),
  vocab("voc-042", "literacy", "noun", "the ability to read and write", "Digital literacy is now as important as traditional literacy.", "education", ["digital literacy", "financial literacy"], ["education", "technology_ai"], "band6_0"),
  vocab("voc-043", "pedagogy", "noun", "the method and practice of teaching", "Modern pedagogy emphasises active learning.", "education", ["pedagogical approach"], ["education"], "band7_0"),
  vocab("voc-044", "enrolment", "noun", "the act of joining a course", "University enrolment has grown in several developing countries.", "education", ["enrolment rates"], ["education", "scholarship_applications"], "band6_0"),
  vocab("voc-045", "scholarship", "noun", "financial support for study, or a detailed study of a topic", "She won a scholarship to study in Europe.", "education", ["scholarship program", "research scholarship"], ["scholarship_applications", "education"], "band5_5"),
  vocab("voc-046", "subsidy", "noun", "money given by the government to support something", "The government provides a subsidy for solar panel installation.", "policy", ["fuel subsidy", "remove subsidy"], ["general_academic", "environment_sustainability", "business_finance"], "band6_5"),
  vocab("voc-047", "fiscal", "adjective", "relating to government money or taxes", "Fiscal policy plays a major role in economic stability.", "policy", ["fiscal policy", "fiscal discipline"], ["business_finance", "law_public_policy"], "band7_0"),
  vocab("voc-048", "monetary", "adjective", "relating to money or currency", "Monetary policy is set by the central bank.", "policy", ["monetary policy", "tight monetary policy"], ["business_finance"], "band7_0"),
  vocab("voc-049", "inflation", "noun", "a general rise in prices", "High inflation has reduced household purchasing power.", "policy", ["rising inflation", "control inflation"], ["business_finance"], "band6_0"),
  vocab("voc-050", "recession", "noun", "a period of temporary economic decline", "The country entered a recession last quarter.", "policy", ["global recession"], ["business_finance"], "band6_0"),
  vocab("voc-051", "inequality", "noun", "lack of equality", "Income inequality has widened in many regions.", "society", ["income inequality", "reduce inequality"], ["general_academic", "law_public_policy", "business_finance"], "band6_5"),
  vocab("voc-052", "poverty", "noun", "the state of being very poor", "Child poverty remains a serious issue.", "society", ["poverty rate", "poverty reduction"], ["general_academic", "law_public_policy"], "band5_5"),
  vocab("voc-053", "migration", "noun", "the act of moving to a new country or region", "Migration policy is a major political topic.", "society", ["migration flows", "economic migration"], ["general_academic", "law_public_policy"], "band6_0"),
  vocab("voc-054", "demographic", "adjective", "relating to population structure", "Demographic change is reshaping the labour market.", "society", ["demographic trends"], ["general_academic", "business_finance"], "band6_5"),
  vocab("voc-055", "urban", "adjective", "relating to a city", "Urban populations are growing rapidly.", "cities", ["urban planning", "urban development"], ["environment_sustainability", "general_academic"], "band6_0"),
  vocab("voc-056", "rural", "adjective", "relating to the countryside", "Rural areas often have less access to services.", "cities", ["rural development", "rural communities"], ["general_academic", "environment_sustainability"], "band5_5"),
  vocab("voc-057", "housing", "noun", "buildings where people live", "Housing supply has not kept up with demand.", "cities", ["affordable housing", "public housing"], ["general_academic", "law_public_policy"], "band6_0"),
  vocab("voc-058", "transportation", "noun", "the act of moving people or goods", "Public transportation is critical for low-income workers.", "cities", ["public transportation", "transportation network"], ["general_academic", "environment_sustainability"], "band6_0"),
  vocab("voc-059", "pollution", "noun", "the presence of harmful substances", "Air pollution remains a major public health concern.", "environment", ["air pollution", "reduce pollution"], ["environment_sustainability"], "band5_5"),
  vocab("voc-060", "ecosystem", "noun", "a community of living things and their environment", "Forests are essential to a healthy ecosystem.", "environment", ["ecosystem services", "marine ecosystem"], ["environment_sustainability"], "band6_5"),
  vocab("voc-061", "habitat", "noun", "the natural home of an animal or plant", "Many species are losing their natural habitat.", "environment", ["habitat loss", "protect habitat"], ["environment_sustainability"], "band6_5"),
  vocab("voc-062", "deforestation", "noun", "the action of clearing forests", "Deforestation contributes to climate change.", "environment", ["rate of deforestation"], ["environment_sustainability"], "band7_0"),
  vocab("voc-063", "climate change", "noun", "long-term shifts in temperature and weather", "Climate change is reshaping agricultural practices.", "environment", ["tackle climate change", "climate change adaptation"], ["environment_sustainability"], "band5_5"),
  vocab("voc-064", "carbon footprint", "noun", "the amount of carbon emitted by an activity", "Many companies now measure their carbon footprint.", "environment", ["reduce carbon footprint"], ["environment_sustainability", "business_finance"], "band6_5"),
  vocab("voc-065", "offset", "verb", "to balance one effect with another", "Some airlines allow passengers to offset their carbon emissions.", "environment", ["offset emissions"], ["environment_sustainability", "business_finance"], "band7_0"),
  vocab("voc-066", "blockchain", "noun", "a digital ledger stored across many computers", "Blockchain technology is used in many financial services.", "technology", ["blockchain technology", "blockchain platform"], ["technology_ai", "business_finance", "law_public_policy"], "band7_0"),
  vocab("voc-067", "cryptocurrency", "noun", "a digital currency secured by cryptography", "Cryptocurrency regulation varies by country.", "finance", ["cryptocurrency market"], ["business_finance", "technology_ai", "law_public_policy"], "band6_5"),
  vocab("voc-068", "fintech", "noun", "technology used in financial services", "Fintech firms are challenging traditional banks.", "finance", ["fintech industry", "fintech regulation"], ["business_finance", "technology_ai"], "band7_0"),
  vocab("voc-069", "startup", "noun", "a young company", "The startup raised funding to expand into new markets.", "business", ["tech startup", "early-stage startup"], ["business_finance", "technology_ai"], "band5_5"),
  vocab("voc-070", "investment", "noun", "money used to earn a return", "Foreign investment has slowed this year.", "finance", ["private investment", "public investment"], ["business_finance"], "band5_5"),
  vocab("voc-071", "shareholder", "noun", "a person who owns shares in a company", "Shareholders are demanding more transparency.", "business", ["shareholder value", "shareholder meeting"], ["business_finance"], "band6_5"),
  vocab("voc-072", "merger", "noun", "the combining of two companies", "The merger was blocked by regulators.", "business", ["proposed merger", "merger approval"], ["business_finance", "law_public_policy"], "band6_5"),
  vocab("voc-073", "competition", "noun", "the act of trying to win or be best", "Competition policy is enforced by the regulator.", "business", ["competition law", "fair competition"], ["business_finance", "law_public_policy"], "band6_0"),
  vocab("voc-074", "monopoly", "noun", "exclusive control of a market", "Antitrust law targets abusive monopoly behaviour.", "business", ["break a monopoly", "natural monopoly"], ["business_finance", "law_public_policy"], "band7_0"),
  vocab("voc-075", "patent", "noun", "a legal right to an invention", "The company filed a patent for the new device.", "law", ["patent protection", "patent application"], ["law_public_policy", "business_finance", "technology_ai"], "band6_5"),
  vocab("voc-076", "copyright", "noun", "the legal right to a creative work", "Copyright protects original literary and artistic works.", "law", ["copyright infringement", "copyright law"], ["law_public_policy", "education"], "band6_0"),
  vocab("voc-077", "trademark", "noun", "a symbol or sign identifying a brand", "The trademark was registered internationally.", "law", ["trademark registration", "trademark protection"], ["law_public_policy", "business_finance"], "band6_5"),
  vocab("voc-078", "litigation", "noun", "the process of taking legal action", "Litigation can be expensive and time-consuming.", "law", ["avoid litigation", "cost of litigation"], ["law_public_policy", "business_finance"], "band7_0"),
  vocab("voc-079", "jurisdiction", "noun", "the official power to make legal decisions", "Cross-border cases raise complex jurisdiction questions.", "law", ["court of jurisdiction", "within the jurisdiction"], ["law_public_policy"], "band7_0"),
  vocab("voc-080", "compliance", "noun", "the act of following rules", "Compliance training is mandatory for all staff.", "business", ["regulatory compliance", "compliance program"], ["law_public_policy", "business_finance"], "band6_5"),
  vocab("voc-081", "stakeholder", "noun", "a person with an interest in a project", "Stakeholders were consulted before the policy was finalised.", "business", ["key stakeholders", "stakeholder engagement"], ["business_finance", "law_public_policy"], "band6_5"),
  vocab("voc-082", "governance", "noun", "the way an organisation is managed", "Good governance is essential for public trust.", "policy", ["corporate governance", "governance reform"], ["law_public_policy", "business_finance"], "band7_0"),
  vocab("voc-083", "oversight", "noun", "the act of watching and checking", "Independent oversight of the agency was strengthened.", "policy", ["regulatory oversight", "lack of oversight"], ["law_public_policy"], "band6_5"),
  vocab("voc-084", "audit", "noun", "an official inspection of accounts", "The company passed the external audit.", "business", ["annual audit", "audit findings"], ["business_finance"], "band6_0"),
  vocab("voc-085", "shortage", "noun", "a lack of something", "There is a shortage of skilled workers in the region.", "work", ["labour shortage", "housing shortage"], ["general_academic", "business_finance"], "band5_5"),
  vocab("voc-086", "demand", "noun", "the desire and ability to buy something", "Demand for electric vehicles is rising.", "business", ["high demand", "meet demand"], ["business_finance"], "band5_5"),
  vocab("voc-087", "supply", "noun", "the amount of something available", "Supply chains have been disrupted.", "business", ["supply chain", "supply shortage"], ["business_finance"], "band5_5"),
  vocab("voc-088", "consumer", "noun", "a person who buys goods or services", "Consumers are increasingly shopping online.", "business", ["consumer behaviour", "consumer rights"], ["business_finance", "law_public_policy"], "band5_5"),
  vocab("voc-089", "advertising", "noun", "the activity of promoting products", "Online advertising has grown rapidly.", "business", ["digital advertising", "advertising standards"], ["business_finance", "technology_ai"], "band5_5"),
  vocab("voc-090", "subscription", "noun", "a regular payment for a service", "Subscription models are common in software.", "business", ["subscription service", "cancel subscription"], ["business_finance", "technology_ai"], "band6_0"),
  vocab("voc-091", "platform", "noun", "an online service that hosts content or transactions", "The platform connects buyers and sellers.", "technology", ["digital platform", "platform economy"], ["technology_ai", "business_finance"], "band6_0"),
  vocab("voc-092", "algorithm", "noun", "a set of rules followed by a computer", "Algorithms decide what content users see.", "technology", ["recommendation algorithm", "algorithmic decision"], ["technology_ai"], "band6_5"),
  vocab("voc-093", "machine learning", "noun", "a type of AI that learns from data", "Machine learning is transforming many industries.", "technology", ["machine learning model"], ["technology_ai", "business_finance"], "band6_5"),
  vocab("voc-094", "deep learning", "noun", "a type of machine learning using neural networks", "Deep learning has improved image recognition.", "technology", ["deep learning model"], ["technology_ai"], "band7_0"),
  vocab("voc-095", "neural network", "noun", "a computer system modelled on the brain", "Neural networks power many modern AI systems.", "technology", ["train a neural network"], ["technology_ai"], "band7_0"),
  vocab("voc-096", "data", "noun", "facts and statistics collected for reference", "Data is now central to decision-making.", "technology", ["data analysis", "data protection"], ["technology_ai", "business_finance"], "band5_5"),
  vocab("voc-097", "dataset", "noun", "a collection of related data", "The dataset includes records from the last five years.", "technology", ["large dataset", "training dataset"], ["technology_ai"], "band6_0"),
  vocab("voc-098", "training", "noun", "the process of teaching a model", "The model required weeks of training.", "technology", ["model training", "training data"], ["technology_ai"], "band6_5"),
  vocab("voc-099", "deployment", "noun", "the act of putting something into use", "The system went into deployment last month.", "technology", ["production deployment"], ["technology_ai", "business_finance"], "band6_5"),
  vocab("voc-100", "integration", "noun", "the act of combining parts into a whole", "The new system requires careful integration with existing tools.", "technology", ["system integration", "seamless integration"], ["technology_ai", "business_finance"], "band6_5"),
];
