// ============================================================================
// WRITING PROMPTS — 15 Task 2 + a small set of Task 1 / micro-drills.
// Stub for prototype. V1 expands to 40+ Task 1 and 60+ Task 2.
// All original. No copied official materials.
// ============================================================================

import type { ContentItem } from "@/lib/types";

export const WRITING_PROMPTS: ContentItem[] = [
  {
    id: "writing-task2-001",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Opinion essay: technology in education",
    topicTags: ["education", "technology"],
    profileTags: ["general_academic", "education", "technology_ai"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Some people believe that digital technology has made classroom learning less effective. To what extent do you agree or disagree?",
      minimumWords: 250,
      planningHints: [
        "State a clear position in the thesis.",
        "Plan two body paragraphs with one concrete example each.",
        "Plan a conclusion that restates the position, not a summary.",
      ],
      sampleStructure: [
        "Thesis: technology is a tool, not a replacement for teachers.",
        "Body 1: technology extends access and supports self-paced learning.",
        "Body 2: technology can fragment attention if used without structure.",
        "Conclusion: classroom effectiveness depends on how technology is used.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-002",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Discussion essay: city transport",
    topicTags: ["cities", "transport", "environment"],
    profileTags: ["general_academic", "environment_sustainability"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Some people argue that governments should prioritise public transport over private cars. Discuss both views and give your own opinion.",
      minimumWords: 250,
      planningHints: [
        "Allocate one body paragraph to each view.",
        "Your opinion should be in the conclusion or in a final short paragraph.",
        "Avoid memorised phrases like 'in conclusion, I would like to say'.",
      ],
      sampleStructure: [
        "Thesis: public transport deserves priority, but private cars still have a role.",
        "Body 1: case for prioritising public transport — congestion, emissions, equity.",
        "Body 2: case for private cars — flexibility, rural access, choice.",
        "Conclusion: priority for public transport, with policies that ease transition.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-003",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Problem/solution: workplace stress",
    topicTags: ["work", "health"],
    profileTags: ["general_academic", "business_finance", "medicine_healthcare"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Many workers report increasing levels of stress in modern workplaces. What are the main causes of this, and what measures could employers take to reduce it?",
      minimumWords: 250,
      planningHints: [
        "Spend one body paragraph on causes, one on solutions.",
        "Use specific examples, not generalisations like 'technology is bad'.",
      ],
      sampleStructure: [
        "Thesis: the main causes are workload and blurred boundaries; the solutions are structural.",
        "Body 1: causes — constant connectivity, performance pressure, job insecurity.",
        "Body 2: solutions — clearer working hours, workload caps, mental health support.",
        "Conclusion: structural changes work better than individual advice.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-004",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Advantages/disadvantages: remote work",
    topicTags: ["work", "technology"],
    profileTags: ["general_academic", "business_finance", "technology_ai"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "More companies are allowing employees to work from home permanently. What are the advantages and disadvantages of this trend?",
      minimumWords: 250,
      planningHints: [
        "Cover both sides fairly before stating your view.",
        "Use one specific example per point.",
      ],
      sampleStructure: [
        "Thesis: permanent remote work is beneficial for many roles, but not for all.",
        "Body 1: advantages — flexibility, lower costs, access to wider talent.",
        "Body 2: disadvantages — isolation, collaboration challenges, blurred work-life boundaries.",
        "Conclusion: hybrid models tend to balance the trade-offs.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-005",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Double question: AI and privacy",
    topicTags: ["technology", "law", "society"],
    profileTags: ["technology_ai", "law_public_policy", "scholarship_applications"],
    difficulty: "band7_0",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Some people argue that artificial intelligence poses serious risks to personal privacy. Why is this a concern, and what could be done to address it?",
      minimumWords: 250,
      planningHints: [
        "Address both questions directly.",
        "Cite one concrete AI application (e.g. facial recognition, recommendation systems).",
      ],
      sampleStructure: [
        "Thesis: privacy risks are real and require both regulation and technical safeguards.",
        "Body 1: why — data collection, profiling, lack of consent.",
        "Body 2: what can be done — data protection laws, transparency requirements, user controls.",
        "Conclusion: a layered approach is more durable than a single fix.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-006",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Opinion essay: regulation of new technology",
    topicTags: ["law", "technology", "society"],
    profileTags: ["law_public_policy", "technology_ai"],
    difficulty: "band7_0",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Should governments regulate artificial intelligence more strictly? To what extent do you agree or disagree?",
      minimumWords: 250,
      planningHints: [
        "Take a position. 'To a certain extent' is not a position.",
        "Distinguish between high-risk and low-risk AI use cases.",
      ],
      sampleStructure: [
        "Thesis: strict regulation is justified for high-risk AI; lighter oversight is enough elsewhere.",
        "Body 1: high-risk use cases — health, criminal justice, infrastructure.",
        "Body 2: lighter approach for low-risk consumer tools.",
        "Conclusion: proportionality is the right principle.",
      ],
      rubricFocus: ["task_response", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-007",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Discussion essay: university relevance",
    topicTags: ["education", "work"],
    profileTags: ["general_academic", "education", "scholarship_applications"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Some people think that a university degree is no longer necessary for many careers. Discuss both views and give your opinion.",
      minimumWords: 250,
      planningHints: [
        "Differentiate careers by field — software vs medicine vs trades.",
        "Avoid a one-sided conclusion.",
      ],
      sampleStructure: [
        "Thesis: a degree is still valuable for many careers, but not the only path.",
        "Body 1: case for degrees — signalling, networks, structured thinking.",
        "Body 2: case against — vocational training, apprenticeships, self-taught paths.",
        "Conclusion: it depends on the field, not the prestige of the institution.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-008",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Problem/solution: housing affordability",
    topicTags: ["cities", "society", "economics"],
    profileTags: ["general_academic", "law_public_policy", "business_finance"],
    difficulty: "band7_0",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "In many cities, housing has become unaffordable for ordinary workers. What are the causes of this, and what could be done to improve it?",
      minimumWords: 250,
      planningHints: [
        "One paragraph on causes, one on solutions.",
        "Include at least one policy mechanism by name (e.g. rent stabilisation, zoning reform).",
      ],
      sampleStructure: [
        "Thesis: the causes are structural; the solutions require policy intervention.",
        "Body 1: causes — supply constraints, speculation, wage stagnation.",
        "Body 2: solutions — zoning reform, public housing investment, tenant protections.",
        "Conclusion: supply expansion is necessary, but must be paired with affordability rules.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-009",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Opinion essay: international travel",
    topicTags: ["culture", "environment", "education"],
    profileTags: ["general_academic", "environment_sustainability", "education"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Some people argue that international travel does more harm than good because of its environmental impact. To what extent do you agree or disagree?",
      minimumWords: 250,
      planningHints: [
        "Quantify at least one claim (e.g. aviation share of emissions).",
        "Distinguish between types of travel.",
      ],
      sampleStructure: [
        "Thesis: aviation's share is significant but the picture is more nuanced.",
        "Body 1: environmental cost — emissions, infrastructure, overtourism.",
        "Body 2: benefits — cultural understanding, education, economies dependent on tourism.",
        "Conclusion: targeted measures (taxes, slow travel) are better than blanket restrictions.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  {
    id: "writing-task2-010",
    skill: "writing",
    type: "writing_task2_essay",
    title: "Advantages/disadvantages: lifelong learning",
    topicTags: ["education", "work", "technology"],
    profileTags: ["general_academic", "education", "scholarship_applications"],
    difficulty: "band6_5",
    estimatedMinutes: 40,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task2",
      prompt: "Many adults return to education while working. What are the advantages and disadvantages of combining work and study?",
      minimumWords: 250,
      planningHints: [
        "Address both employer and employee perspectives.",
        "Use specific examples (online MBAs, evening courses, etc.).",
      ],
      sampleStructure: [
        "Thesis: the combination is valuable but demanding, and outcomes depend on support.",
        "Body 1: advantages — career mobility, applied learning, personal growth.",
        "Body 2: disadvantages — time pressure, fatigue, family strain.",
        "Conclusion: success depends on institutional support and clear personal goals.",
      ],
      rubricFocus: ["task_response", "coherence", "lexical", "grammar"],
    },
  },
  // -------- Micro / drill prompts --------
  {
    id: "writing-micro-001",
    skill: "writing",
    type: "writing_micro_thesis",
    title: "Thesis upgrade: technology in education",
    topicTags: ["education", "technology"],
    profileTags: ["general_academic", "education", "technology_ai"],
    difficulty: "band6_0",
    estimatedMinutes: 5,
    cooldownDays: 14,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "micro_thesis",
      prompt: "Rewrite this thesis to be clearer and more specific.\n\nOriginal: 'Technology has many effects on education.'",
      minimumWords: 25,
    },
  },
  {
    id: "writing-micro-002",
    skill: "writing",
    type: "writing_micro_thesis",
    title: "Thesis upgrade: city policy",
    topicTags: ["cities", "policy"],
    profileTags: ["general_academic", "law_public_policy"],
    difficulty: "band6_0",
    estimatedMinutes: 5,
    cooldownDays: 14,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "micro_thesis",
      prompt: "Rewrite this thesis to be clearer and more specific.\n\nOriginal: 'Cities face many problems today.'",
      minimumWords: 25,
    },
  },
  {
    id: "writing-paragraph-001",
    skill: "writing",
    type: "writing_paragraph_drill",
    title: "Paragraph drill: second body paragraph",
    topicTags: ["writing_skill"],
    profileTags: ["general_academic"],
    difficulty: "band6_0",
    estimatedMinutes: 6,
    cooldownDays: 14,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "paragraph_drill",
      prompt: "Write ONE body paragraph (80–120 words) for this thesis: 'Governments should regulate high-risk AI while supporting low-risk innovation.'\n\nYour paragraph should give ONE concrete example and reach a clear mini-conclusion.",
      minimumWords: 80,
    },
  },
  {
    id: "writing-paragraph-002",
    skill: "writing",
    type: "writing_paragraph_drill",
    title: "Paragraph drill: topic sentence",
    topicTags: ["writing_skill"],
    profileTags: ["general_academic"],
    difficulty: "band6_0",
    estimatedMinutes: 5,
    cooldownDays: 14,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "paragraph_drill",
      prompt: "Write a topic sentence for a paragraph that argues: 'Online courses are not always cheaper than classroom courses in the long run.'",
      minimumWords: 20,
    },
  },
  {
    id: "writing-task1-001",
    skill: "writing",
    type: "writing_task1_report",
    title: "Line graph: global internet users",
    topicTags: ["technology", "society"],
    profileTags: ["general_academic", "technology_ai"],
    difficulty: "band6_5",
    estimatedMinutes: 20,
    cooldownDays: 30,
    reviewStatus: "approved",
    copyrightStatus: "original",
    payload: {
      taskType: "task1",
      prompt: "The line graph below shows the percentage of the global population using the internet from 2000 to 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\n[Graph description: 2000 — 7%; 2005 — 17%; 2010 — 34%; 2015 — 48%; 2020 — 64%. Growth in developed regions plateaued after 2015; growth in developing regions accelerated after 2010.]",
      minimumWords: 150,
      planningHints: [
        "Start with a one-sentence overview.",
        "Report the highest and lowest figures.",
        "Compare regions, not just years.",
      ],
    },
  },
];
