"use client";

import Link from "next/link";

export function AiDisclosureNotice({
  accepted,
  onAccept,
}: {
  accepted: boolean;
  onAccept: () => void;
}) {
  if (accepted) {
    return (
      <div className="card border-success/30 bg-success/5 p-4 text-small text-ink-muted">
        AI disclosure accepted. Feedback may be generated by an AI provider.
      </div>
    );
  }

  return (
    <div className="card border-warn/40 bg-warn/5 p-4 text-small">
      <p className="font-medium text-warn">Before AI feedback</p>
      <p className="mt-2 text-ink-muted">
        Your answer may be sent to an AI provider to generate feedback. Do not submit sensitive personal information.
      </p>
      <div className="mt-3 flex flex-wrap items-center gap-3">
        <button type="button" onClick={onAccept} className="btn-accent btn-sm">
          I understand
        </button>
        <Link href="/privacy" className="text-tiny text-ink-muted hover:text-ink">
          Privacy details
        </Link>
      </div>
    </div>
  );
}
